site_name: efarmer
site_description: Api for farmer sales market
repo_url: https://github.com/oskarsakol/eFarmer
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/oskarsakol">oskarsakol</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
