# Generated by Django 2.2.8 on 2020-01-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200120_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(default=-71, max_length=10),
            preserve_default=False,
        ),
    ]
