# Generated by Django 2.2.8 on 2020-01-20 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_auto_20200120_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='user_pk',
            new_name='user',
        ),
    ]
