# Generated by Django 2.2.8 on 2020-01-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_auto_20200120_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='date_from',
            new_name='auction_from',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='date_to',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='auction_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
